version: 2
updates:
  - package-ecosystem: pub
    directory: /app-mobile
    target-branch: dev
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
  - package-ecosystem: maven
    directory: /backend
    target-branch: dev
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
  - package-ecosystem: github-actions
    directory: /
    target-branch: dev
    schedule:
      interval: monthly
    open-pull-requests-limit: 3
